service: abstractplay-homeworlds-diagrams

frameworkVersion: "2 || 3"

provider:
    name: aws
    runtime: nodejs14.x
    stage: dev
    region: us-east-1
    profile: AbstractPlayDev

plugins:
    - serverless-finch

custom:
    client:
        bucketName: hwdiagrams.abstractplay.com
        distributionFolder: ./dist
        indexDocument: index.html
