/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The schema describing the input required for the Homeworlds diagram generator
 */
export interface HomeworldsDiagramGeneratorInput {
  /**
   * The number of players in the game. This is only needed if you're rendering a game where one of the players has been eliminated. Otherwise, the number of players will be calculated by the number of homeworld systems.
   */
  numPlayers: number;
  /**
   * The list of systems and ships they contain
   */
  universe: System[];
}
export interface System {
  /**
   * Optional. If not provided, an auto-generated one will be provided.
   */
  name?: string;
  /**
   * Omit in periphery systems
   */
  owner?: "N" | "E" | "S" | "W";
  /**
   * @maxItems 2
   */
  stars: [] | [string] | [string, string];
  /**
   * @maxItems 24
   */
  ships: string[];
}
